apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fulfill-core
  name: fulfill-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulfill-core
  template:
    metadata:
      labels:
        app: fulfill-core
    spec:
      containers:
      - image: rajkrishnanr/f1:9e6be0086831ded483b704b4235a30118fe3b307
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 8000
          name: django-wsgi
