apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulfill-core
  labels:
    app: fulfill-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulfill-core
  template:
    metadata:
      labels:
        app: fulfill-core
    spec:
      containers:
        - image: rajkrishnanr/f1:0b030e56c4c08beb8e760d713832697c4adc0129
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 8000
              name: django-wsgi
