apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fulfill-core
  name: fulfill-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fulfill-core
  template:
    metadata:
      labels:
        app: fulfill-core
    spec:
      containers:
      - image: rajkrishnanr/f1:5d062b395c3bfe00234881715d97b3cde72ec056
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 8000
          name: django-wsgi
